{% set version = "1.8" %}

package:
  name: tensorboardx
  version: {{ version }}+db1

source:
  fn: tensorboardX-{{ version }}.tar.gz
  url: https://github.com/lanpa/tensorboardX/archive/v{{ version }}.tar.gz
  sha256: c7b5dca231afccc68a95d03b8ff81fa9931d4a30542e4491d31cf009572c4672
  patches:
    - 0001-fixed-regression-of-206-489.patch

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - protobuf >=3.2.0
    - six

test:
  requires:
    - pytest
    - matplotlib
  imports:
    - tensorboardX

about:
  home: https://github.com/lanpa/tensorboardX
  license: MIT
  summary: TensorBoardX lets you watch Tensors Flow without Tensorflow
  dev_url: https://github.com/lanpa/tensorboardX

